
# I took a hint from Astropy and Sunpy, who  set the language to c because
# python isn't supported on the MacOS X nodes on Travis.
# I guess it's irrelevant, though, since we immediately install python using conda.
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# whitelist
branches:
  only:
    - master
    - dev

# command to install dependencies
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7-dev" ]]; then
      conda create -q -n test-environment python=3.7 scipy numpy matplotlib nose pytables flake8
    else
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy numpy matplotlib nose pytables flake8
    fi
  - source activate test-environment
  - pip install coveralls
  - pip install pint
  - python setup.py install

script:
  - nosetests pyrk

after_success:
  - coveralls
  - flake8 examples pyrk
